// System-recap block generator tests.
// Run: bun test  (from this directory)
import { test, expect } from "bun:test";
import { buildBlock, upsert } from "./recap.ts";

const report = {
  meta: { headSha: "abc1234def" },
  verdict: { decision: "comment" },
  systemChange: {
    mapPath: "docs/project/primitives.yaml",
    overall: "extends",
    mapUpdated: true,
    primitives: [
      {
        id: "prd",
        name: "PRD",
        area: "data",
        classification: "extends",
        files: ["convex/sharedPrds.ts"],
        invariantsTouched: ["Agents may set draft/in_review but never approve."],
        relatesTo: ["kano-category"],
      },
      {
        id: "kano-category",
        name: "Kano category",
        area: "data",
        classification: "composes",
        files: ["src/components/kano/kano-badge.tsx"],
      },
    ],
    added: [],
  },
};

test("buildBlock produces a marker-wrapped details block with mermaid and table", () => {
  const block = buildBlock(report);
  expect(block.startsWith("<!-- system-recap:start -->")).toBe(true);
  expect(block.endsWith("<!-- system-recap:end -->")).toBe(true);
  expect(block).toContain("```mermaid");
  expect(block).toContain('prd["PRD"]:::extends');
  expect(block).toContain("kano-category --- prd");
  expect(block.match(/ --- /g)?.length).toBe(1);
  expect(block).toContain("</summary>\n\n```mermaid");
  expect(block).toContain("| PRD | data | extends |");
  expect(block).toContain("never approve");
  expect(block).toContain("EXTENDS");
});

test("buildBlock neutralizes hostile names in mermaid and table cells", () => {
  const hostile = JSON.parse(JSON.stringify(report));
  hostile.systemChange.primitives[0].name = 'x"]; click evil "<script>';
  const block = buildBlock(hostile);
  expect(block).not.toContain("<script>");
  expect(block).not.toContain('"];');
});

test("buildBlock throws without a systemChange section", () => {
  expect(() => buildBlock({ verdict: { decision: "comment" } })).toThrow("no systemChange");
});

test("buildBlock footer: attributed with full identity, plain stamp otherwise", () => {
  const attributed = buildBlock(
    { ...report, meta: { ...report.meta, model: "Claude Fable 5", harness: "Claude Code" } },
    "octo"
  );
  expect(attributed).toContain(
    "<sub>🤖 Written on behalf of @octo by Claude Fable 5 via Claude Code · review-pr · abc1234</sub>"
  );
  // login without meta identity (older findings files) falls back, no variant marker
  expect(buildBlock(report, "octo")).toContain("<sub>generated by review-pr · abc1234</sub>");
  expect(buildBlock(report)).toContain("<sub>generated by review-pr · abc1234</sub>");
});

test("upsert replaces an existing block in place and appends when absent", () => {
  const block = buildBlock(report);
  const body = `Intro text\n\n${block}\n\nOutro`;
  const nextBlock = buildBlock({ ...report, verdict: { decision: "approve" } });
  const replaced = upsert(body, nextBlock);
  expect(replaced).toContain("review: approve");
  expect(replaced).not.toContain("review: comment");
  expect(replaced.match(/system-recap:start/g)?.length).toBe(1);
  expect(replaced).toContain("Intro text");
  expect(replaced).toContain("Outro");

  const appended = upsert("Plain body", block);
  expect(appended.startsWith("Plain body")).toBe(true);
  expect(appended).toContain("system-recap:start");
});
