// System-recap block generator tests.
// Run: bun test  (from this directory)
import { test, expect } from "bun:test";
import { buildBlock, upsert } from "./recap.ts";

const report = {
  meta: { headSha: "abc1234def" },
  verdict: { decision: "comment" },
  systemChange: {
    mapPath: "docs/project/primitives.yaml",
    overall: "extends",
    mapUpdated: true,
    primitives: [
      {
        id: "prd",
        name: "PRD",
        area: "data",
        classification: "extends",
        files: ["convex/sharedPrds.ts"],
        invariantsTouched: ["Agents may set draft/in_review but never approve."],
        relatesTo: ["kano-category"],
      },
      {
        id: "kano-category",
        name: "Kano category",
        area: "data",
        classification: "composes",
        files: ["src/components/kano/kano-badge.tsx"],
      },
    ],
    added: [],
  },
};

test("buildBlock produces a marker-wrapped details block with mermaid and table", () => {
  const block = buildBlock(report);
  expect(block.startsWith("<!-- system-recap:start -->")).toBe(true);
  expect(block.endsWith("<!-- system-recap:end -->")).toBe(true);
  expect(block).toContain("```mermaid");
  expect(block).toContain('prd["PRD"]:::extends');
  expect(block).toContain("kano-category --- prd");
  expect(block.match(/ --- /g)?.length).toBe(1);
  expect(block).toContain("</summary>\n\n```mermaid");
  expect(block).toContain("| PRD | data | extends |");
  expect(block).toContain("never approve");
  expect(block).toContain("EXTENDS");
});

test("buildBlock neutralizes hostile names in mermaid and table cells", () => {
  const hostile = JSON.parse(JSON.stringify(report));
  hostile.systemChange.primitives[0].name = 'x"]; click evil "<script>';
  const block = buildBlock(hostile);
  expect(block).not.toContain("<script>");
  expect(block).not.toContain('"];');
});

test("long invariants clip on a word boundary with an ellipsis, not mid-word", () => {
  const original =
    "Agents may set draft or in review but never approve because approval requires every section ready or not applicable with at least one ready and the guard lives in isPrdApprovable which every writer must call";
  const long = JSON.parse(JSON.stringify(report));
  long.systemChange.primitives[0].invariantsTouched = [original];
  const block = buildBlock(long);
  const line = block.split("\n").find((l) => l.includes("Agents may set"))!;
  expect(line).toContain("…"); // clipped with ellipsis
  const prefix = line.slice(line.indexOf("Agents"), line.indexOf("…"));
  // The kept text must be a prefix of the original that ends exactly at a word
  // boundary — i.e. the next character in the original is a space (not mid-word).
  expect(original.startsWith(prefix)).toBe(true);
  expect(original[prefix.length]).toBe(" ");
  expect(prefix.endsWith(" ")).toBe(false); // no dangling space before the ellipsis
  expect(prefix.length).toBeLessThanOrEqual(160);
});

test("buildBlock throws without a systemChange section", () => {
  expect(() => buildBlock({ verdict: { decision: "comment" } })).toThrow("no systemChange");
});

test("buildBlock footer: attributed with full identity, plain stamp otherwise", () => {
  const attributed = buildBlock(
    { ...report, meta: { ...report.meta, model: "Claude Fable 5", harness: "Claude Code" } },
    "octo"
  );
  expect(attributed).toContain(
    "<sub>🤖 Written on behalf of @octo by Claude Fable 5 via Claude Code · review-pr · abc1234</sub>"
  );
  // login without meta identity (older findings files) falls back, no variant marker
  expect(buildBlock(report, "octo")).toContain("<sub>generated by review-pr · abc1234</sub>");
  expect(buildBlock(report)).toContain("<sub>generated by review-pr · abc1234</sub>");
});

test("upsert replaces an existing block in place and appends when absent", () => {
  const block = buildBlock(report);
  const body = `Intro text\n\n${block}\n\nOutro`;
  const nextBlock = buildBlock({ ...report, verdict: { decision: "approve" } });
  const replaced = upsert(body, nextBlock);
  expect(replaced).toContain("review: approve");
  expect(replaced).not.toContain("review: comment");
  expect(replaced.match(/system-recap:start/g)?.length).toBe(1);
  expect(replaced).toContain("Intro text");
  expect(replaced).toContain("Outro");

  const appended = upsert("Plain body", block);
  expect(appended.startsWith("Plain body")).toBe(true);
  expect(appended).toContain("system-recap:start");
});
